"""added email_verified and email_token to User

Revision ID: a1b1158c8c61
Revises: 
Create Date: 2025-08-19 12:59:31.624094

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1b1158c8c61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True, default=False))
	op.add_column('users', sa.Column('email_token', sa.String(), nullable=True))
	op.add_column('users', sa.Column('otp_expiration', sa.DateTime, nullable=True))


# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('users', 'email_token')
	op.drop_column('users', 'email_verified')
	op.drop_column('users', 'otp_expiration')
# ### end Alembic commands ###
